# Generated by Django 5.1.4 on 2025-01-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('head_of_buying', 'Head Of Buying'), ('senior_team_lead', 'Senior Team Lead'), ('middle_team_lead', 'Middle Team Lead'), ('junior_team_lead', 'Junior Team Lead'), ('solo_buyer', 'Solo Buyer'), ('senior_buyer', 'Senior Buyer'), ('middle_buyer', 'Middle Buyer'), ('junior_buyer', 'Junior Buyer')], default='solo_buyer', max_length=40, verbose_name='Роль'),
        ),
    ]
