# Generated by Django 5.1.4 on 2025-01-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('head_of_buying', 'Head Of Buying'), ('senior_team_lead', 'Senior Team Lead'), ('middle_team_lead', 'Middle Team Lead'), ('junior_team_lead', 'Junior Team Lead'), ('senior_buyer', 'Senior Buyer'), ('middle_buyer', 'Middle Buyer'), ('junior_buyer', 'Junior Buyer'), ('solo_buyer', 'Solo Buyer'), ('lead_web_developer', 'Lead Web Developer'), ('web_developer', 'Web Developer'), ('lead_designer', 'Lead Designer'), ('designer', 'Designer'), ('lead_video_creator', 'Lead Video Creator'), ('video_creator', 'Video Creator')], default='solo_buyer', max_length=40, verbose_name='Роль'),
        ),
    ]
